import {
  getSeriesPublicationStatus,
  isEpisodePubliclyVisible,
  pickText,
  type EpisodeRow,
  type SeriesRow,
} from "@/features/write/writeShared";
import { generateNemoRecordingForEpisode } from "@/lib/recording/nemoGeneration";
import { normalizeRecordingPermissionMode } from "@/lib/recording/recordingEntry";
import { createAdminClient } from "@/lib/supabase/admin";

type AdminSupabase = ReturnType<typeof createAdminClient>;

type RecordingRow = Record<string, unknown> & {
  id: string;
  episode_id?: string | null;
  episodeId?: string | null;
  reader_id?: string | null;
  reader_user_id?: string | null;
  readerUserId?: string | null;
  reader_name?: string | null;
  narrator_name?: string | null;
  display_name?: string | null;
  speaker_name?: string | null;
  is_public?: boolean | null;
  public?: boolean | null;
};

type NemoAutoGenerationConfig = {
  userId: string;
  narratorName: string;
  speakerId: number;
};

export type NemoAutoGenerationStepResult = {
  ok: boolean;
  status:
    | "generated"
    | "none_missing"
    | "busy"
    | "config_missing"
    | "skipped";
  generatedEpisodeId?: string;
  reason?: string;
};

declare global {
  var __libreadNemoAutogenRunning: boolean | undefined;
}

function parseSpeakerId(rawValue: string, fallbackRawValue?: string): number | null {
  const candidates = [rawValue, fallbackRawValue ?? ""];

  for (const candidate of candidates) {
    if (!candidate) continue;

    const parsed = Number(candidate);

    if (Number.isInteger(parsed) && parsed >= 0) {
      return parsed;
    }
  }

  return null;
}

function resolveNemoAutoGenerationConfig(): NemoAutoGenerationConfig | null {
  const userId = (process.env.VOICEVOX_NEMO_AUTOGEN_USER_ID ?? "").trim();
  const narratorName =
    (process.env.VOICEVOX_NEMO_AUTOGEN_NARRATOR_NAME ?? "").trim() ||
    "VOICEVOX Nemo / ノーマル";
  const speakerId = parseSpeakerId(
    (process.env.VOICEVOX_NEMO_AUTOGEN_SPEAKER_ID ?? "").trim(),
    process.env.VOICEVOX_NEMO_DEFAULT_SPEAKER
  );

  if (!userId || speakerId === null) {
    return null;
  }

  return {
    userId,
    narratorName,
    speakerId,
  };
}

function isPublicRecording(recording: RecordingRow): boolean {
  if (recording.is_public === false) return false;
  if (recording.public === false) return false;
  return true;
}

function getRecordingEpisodeId(recording: RecordingRow): string {
  return pickText(recording.episode_id, recording.episodeId);
}

function getRecordingReaderId(recording: RecordingRow): string {
  return pickText(
    recording.reader_id,
    recording.reader_user_id,
    recording.readerUserId
  );
}

function getRecordingReaderName(recording: RecordingRow): string {
  return (
    pickText(
      recording.reader_name,
      recording.narrator_name,
      recording.display_name,
      recording.speaker_name
    ) || "朗読者未設定"
  );
}

function hasAutoGeneratedRecordingForEpisode(
  recordings: RecordingRow[],
  episodeId: string,
  config: NemoAutoGenerationConfig
): boolean {
  return recordings.some((recording) => {
    if (!isPublicRecording(recording)) return false;
    if (getRecordingEpisodeId(recording) !== episodeId) return false;

    return (
      getRecordingReaderId(recording) === config.userId ||
      getRecordingReaderName(recording) === config.narratorName
    );
  });
}

async function fetchSeries(
  supabase: AdminSupabase,
  seriesId: string
): Promise<SeriesRow | null> {
  const { data, error } = await supabase
    .from("series")
    .select("*")
    .eq("id", seriesId)
    .maybeSingle();

  if (error || !data) {
    return null;
  }

  return data as SeriesRow;
}

async function fetchEpisodesBySeriesId(
  supabase: AdminSupabase,
  seriesId: string
): Promise<EpisodeRow[]> {
  const firstTry = await supabase
    .from("episodes")
    .select("*")
    .eq("series_id", seriesId);

  if (!firstTry.error) {
    return (firstTry.data ?? []) as EpisodeRow[];
  }

  const secondTry = await supabase
    .from("episodes")
    .select("*")
    .eq("seriesId", seriesId);

  if (!secondTry.error) {
    return (secondTry.data ?? []) as EpisodeRow[];
  }

  return [];
}

async function fetchRecordingsByEpisodeId(
  supabase: AdminSupabase,
  episodeId: string
): Promise<RecordingRow[]> {
  const firstTry = await supabase
    .from("recordings")
    .select("*")
    .eq("episode_id", episodeId);

  if (!firstTry.error) {
    return (firstTry.data ?? []) as RecordingRow[];
  }

  const secondTry = await supabase
    .from("recordings")
    .select("*")
    .eq("episodeId", episodeId);

  if (!secondTry.error) {
    return (secondTry.data ?? []) as RecordingRow[];
  }

  return [];
}

export async function runNemoAutoGenerationStep(args: {
  seriesId: string;
  episodeIds: string[];
}): Promise<NemoAutoGenerationStepResult> {
  const { seriesId, episodeIds } = args;
  const config = resolveNemoAutoGenerationConfig();

  if (!config) {
    return {
      ok: false,
      status: "config_missing",
      reason: "autogen_env_missing",
    };
  }

  if (globalThis.__libreadNemoAutogenRunning) {
    return {
      ok: true,
      status: "busy",
    };
  }

  globalThis.__libreadNemoAutogenRunning = true;

  try {
    const adminSupabase = createAdminClient();
    const series = await fetchSeries(adminSupabase, seriesId);

    if (!series) {
      return {
        ok: false,
        status: "skipped",
        reason: "series_not_found",
      };
    }

    if (getSeriesPublicationStatus(series) !== "public") {
      return {
        ok: true,
        status: "skipped",
        reason: "series_not_public",
      };
    }

    const permissionMode = normalizeRecordingPermissionMode(
      series.recording_permission_mode
    );

    if (permissionMode !== "open") {
      return {
        ok: true,
        status: "skipped",
        reason: "permission_mode_not_open",
      };
    }

    const episodes = (await fetchEpisodesBySeriesId(adminSupabase, seriesId))
      .filter((episode) => isEpisodePubliclyVisible(episode))
      .filter((episode) => episodeIds.includes(episode.id));

    for (const episode of episodes) {
      const recordings = await fetchRecordingsByEpisodeId(adminSupabase, episode.id);

      if (hasAutoGeneratedRecordingForEpisode(recordings, episode.id, config)) {
        continue;
      }

      await generateNemoRecordingForEpisode({
        supabase: adminSupabase,
        userId: config.userId,
        seriesId,
        episodeId: episode.id,
        narratorName: config.narratorName,
        speakerId: config.speakerId,
      });

      return {
        ok: true,
        status: "generated",
        generatedEpisodeId: episode.id,
      };
    }

    return {
      ok: true,
      status: "none_missing",
    };
  } finally {
    globalThis.__libreadNemoAutogenRunning = false;
  }
}