import {
  getSeriesPublicationStatus,
  isEpisodePubliclyVisible,
  pickText,
  type EpisodeRow,
  type SeriesRow,
} from "@/features/write/writeShared";
import { generateNemoRecordingForEpisode } from "@/lib/recording/nemoGeneration";
import { normalizeRecordingPermissionMode } from "@/lib/recording/recordingEntry";
import { createAdminClient } from "@/lib/supabase/admin";

type AdminSupabase = ReturnType<typeof createAdminClient>;

type RecordingRow = Record<string, unknown> & {
  id: string;
  episode_id?: string | null;
  episodeId?: string | null;
  reader_id?: string | null;
  reader_user_id?: string | null;
  readerUserId?: string | null;
  reader_name?: string | null;
  narrator_name?: string | null;
  display_name?: string | null;
  speaker_name?: string | null;
  is_public?: boolean | null;
  public?: boolean | null;
};

export type NemoAutoGenerationTriggerMode = "public_open" | "approval_approved";

export type NemoAutoGenerationResult = {
  triggered: boolean;
  generatedEpisodeIds: string[];
  skippedEpisodeIds: string[];
  failedEpisodeIds: string[];
  reason: string | null;
};

type NemoAutoGenerationConfig = {
  userId: string;
  narratorName: string;
  speakerId: number;
};

function parseSpeakerId(rawValue: string, fallbackRawValue?: string): number | null {
  const candidates = [rawValue, fallbackRawValue ?? ""];

  for (const candidate of candidates) {
    if (!candidate) continue;

    const parsed = Number(candidate);

    if (Number.isInteger(parsed) && parsed >= 0) {
      return parsed;
    }
  }

  return null;
}

function resolveNemoAutoGenerationConfig(): NemoAutoGenerationConfig | null {
  const userId = (process.env.VOICEVOX_NEMO_AUTOGEN_USER_ID ?? "").trim();
  const narratorName =
    (process.env.VOICEVOX_NEMO_AUTOGEN_NARRATOR_NAME ?? "").trim() ||
    "VOICEVOX Nemo / ノーマル";
  const speakerId = parseSpeakerId(
    (process.env.VOICEVOX_NEMO_AUTOGEN_SPEAKER_ID ?? "").trim(),
    process.env.VOICEVOX_NEMO_DEFAULT_SPEAKER
  );

  if (!userId || speakerId === null) {
    return null;
  }

  return {
    userId,
    narratorName,
    speakerId,
  };
}

function isPublicRecording(recording: RecordingRow): boolean {
  if (recording.is_public === false) return false;
  if (recording.public === false) return false;
  return true;
}

function getRecordingEpisodeId(recording: RecordingRow): string {
  return pickText(recording.episode_id, recording.episodeId);
}

function getRecordingReaderId(recording: RecordingRow): string {
  return pickText(
    recording.reader_id,
    recording.reader_user_id,
    recording.readerUserId
  );
}

function getRecordingReaderName(recording: RecordingRow): string {
  return (
    pickText(
      recording.reader_name,
      recording.narrator_name,
      recording.display_name,
      recording.speaker_name
    ) || "朗読者未設定"
  );
}

function hasAutoGeneratedRecordingForEpisode(
  recordings: RecordingRow[],
  episodeId: string,
  config: NemoAutoGenerationConfig
): boolean {
  return recordings.some((recording) => {
    if (!isPublicRecording(recording)) return false;
    if (getRecordingEpisodeId(recording) !== episodeId) return false;

    return (
      getRecordingReaderId(recording) === config.userId ||
      getRecordingReaderName(recording) === config.narratorName
    );
  });
}

async function fetchSeries(
  supabase: AdminSupabase,
  seriesId: string
): Promise<SeriesRow | null> {
  const { data, error } = await supabase
    .from("series")
    .select("*")
    .eq("id", seriesId)
    .maybeSingle();

  if (error || !data) {
    return null;
  }

  return data as SeriesRow;
}

async function fetchEpisodesBySeriesId(
  supabase: AdminSupabase,
  seriesId: string
): Promise<EpisodeRow[]> {
  const firstTry = await supabase
    .from("episodes")
    .select("*")
    .eq("series_id", seriesId);

  if (!firstTry.error) {
    return (firstTry.data ?? []) as EpisodeRow[];
  }

  const secondTry = await supabase
    .from("episodes")
    .select("*")
    .eq("seriesId", seriesId);

  if (!secondTry.error) {
    return (secondTry.data ?? []) as EpisodeRow[];
  }

  return [];
}

async function fetchRecordingsBySeriesId(
  supabase: AdminSupabase,
  seriesId: string
): Promise<RecordingRow[]> {
  const firstTry = await supabase
    .from("recordings")
    .select("*")
    .eq("series_id", seriesId);

  if (!firstTry.error) {
    return (firstTry.data ?? []) as RecordingRow[];
  }

  const secondTry = await supabase
    .from("recordings")
    .select("*")
    .eq("seriesId", seriesId);

  if (!secondTry.error) {
    return (secondTry.data ?? []) as RecordingRow[];
  }

  return [];
}

export async function triggerNemoAutoGenerationForEpisodeIds(args: {
  seriesId: string;
  episodeIds: string[];
  triggerMode: NemoAutoGenerationTriggerMode;
}): Promise<NemoAutoGenerationResult> {
  const { seriesId, episodeIds, triggerMode } = args;
  const config = resolveNemoAutoGenerationConfig();

  if (!config) {
    return {
      triggered: false,
      generatedEpisodeIds: [],
      skippedEpisodeIds: [],
      failedEpisodeIds: [],
      reason: "autogen_env_missing",
    };
  }

  if (episodeIds.length === 0) {
    return {
      triggered: false,
      generatedEpisodeIds: [],
      skippedEpisodeIds: [],
      failedEpisodeIds: [],
      reason: "no_episode_ids",
    };
  }

  const adminSupabase = createAdminClient();
  const series = await fetchSeries(adminSupabase, seriesId);

  if (!series) {
    return {
      triggered: false,
      generatedEpisodeIds: [],
      skippedEpisodeIds: [],
      failedEpisodeIds: [],
      reason: "series_not_found",
    };
  }

  if (getSeriesPublicationStatus(series) !== "public") {
    return {
      triggered: false,
      generatedEpisodeIds: [],
      skippedEpisodeIds: [],
      failedEpisodeIds: [],
      reason: "series_not_public",
    };
  }

  const permissionMode = normalizeRecordingPermissionMode(
    series.recording_permission_mode
  );

  if (triggerMode === "public_open" && permissionMode !== "open") {
    return {
      triggered: false,
      generatedEpisodeIds: [],
      skippedEpisodeIds: [],
      failedEpisodeIds: [],
      reason: "permission_mode_not_open",
    };
  }

  if (
    triggerMode === "approval_approved" &&
    permissionMode !== "approval_required"
  ) {
    return {
      triggered: false,
      generatedEpisodeIds: [],
      skippedEpisodeIds: [],
      failedEpisodeIds: [],
      reason: "permission_mode_not_approval_required",
    };
  }

  const episodes = (await fetchEpisodesBySeriesId(adminSupabase, seriesId))
    .filter((episode) => isEpisodePubliclyVisible(episode))
    .filter((episode) => episodeIds.includes(episode.id));

  if (episodes.length === 0) {
    return {
      triggered: false,
      generatedEpisodeIds: [],
      skippedEpisodeIds: [],
      failedEpisodeIds: [],
      reason: "no_public_episodes",
    };
  }

  const recordings = await fetchRecordingsBySeriesId(adminSupabase, seriesId);

  const generatedEpisodeIds: string[] = [];
  const skippedEpisodeIds: string[] = [];
  const failedEpisodeIds: string[] = [];

  for (const episode of episodes) {
    if (
      hasAutoGeneratedRecordingForEpisode(recordings, episode.id, config)
    ) {
      skippedEpisodeIds.push(episode.id);
      continue;
    }

    try {
      await generateNemoRecordingForEpisode({
        supabase: adminSupabase,
        userId: config.userId,
        seriesId,
        episodeId: episode.id,
        narratorName: config.narratorName,
        speakerId: config.speakerId,
      });

      generatedEpisodeIds.push(episode.id);
    } catch (error) {
      console.error("[nemo auto generation failed]", {
        triggerMode,
        seriesId,
        episodeId: episode.id,
        error,
      });

      failedEpisodeIds.push(episode.id);
    }
  }

  return {
    triggered: generatedEpisodeIds.length > 0,
    generatedEpisodeIds,
    skippedEpisodeIds,
    failedEpisodeIds,
    reason: null,
  };
}