alter table public.users
  add column if not exists x_url text;

alter table public.users
  add column if not exists note_url text;

create table if not exists public.author_follows (
  id bigint generated by default as identity primary key,
  follower_user_id uuid not null,
  followed_author_id uuid not null,
  created_at timestamptz not null default now(),
  unique (follower_user_id, followed_author_id)
);

create index if not exists idx_author_follows_follower_user_id
  on public.author_follows (follower_user_id);

create index if not exists idx_author_follows_followed_author_id
  on public.author_follows (followed_author_id);

create table if not exists public.author_profile_likes (
  id bigint generated by default as identity primary key,
  author_id uuid not null,
  user_id uuid not null,
  created_at timestamptz not null default now(),
  unique (author_id, user_id)
);

create index if not exists idx_author_profile_likes_author_id
  on public.author_profile_likes (author_id);

create index if not exists idx_author_profile_likes_user_id
  on public.author_profile_likes (user_id);

create table if not exists public.reader_card_likes (
  id bigint generated by default as identity primary key,
  series_id uuid not null,
  reader_key text not null,
  user_id uuid not null,
  created_at timestamptz not null default now(),
  unique (series_id, reader_key, user_id)
);

create index if not exists idx_reader_card_likes_series_reader
  on public.reader_card_likes (series_id, reader_key);

create index if not exists idx_reader_card_likes_user_id
  on public.reader_card_likes (user_id);